<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Expense>
 */
class ExpenseFactory extends Factory
{
    private $foodAndDrinkItems = [
        'Cheese Platter',
        'Charcuterie Board',
        'Chips and Dip',
        'Guacamole',
        'Salsa',
        'Hummus',
        'Vegetable Platter',
        'Fruit Platter',
        'Spinach Artichoke Dip',
        'Buffalo Wings',
        'Mozzarella Sticks',
        'Jalapeño Poppers',
        'Mini Quiches',
        'Spring Rolls',
        'Stuffed Mushrooms',
        'Cheese-Stuffed Jalapeños',
        'Chicken Tenders',
        'Pigs in a Blanket',
        'Meatballs',
        'Chicken Wings (BBQ or Spicy)',
        'Pulled Pork Sliders',
        'Beef Sliders',
        'Veggie Burgers',
        'Sandwich Platter',
        'Bagels with Cream Cheese',
        'Deviled Eggs',
        'Potato Salad',
        'Macaroni Salad',
        'Coleslaw',
        'Caesar Salad',
        'Caprese Salad',
        'Greek Salad',
        'Cauliflower Bites',
        'Tacos (Hard Shell and Soft Shell)',
        'Mini Burritos',
        'Nachos with Cheese and Jalapeños',
        'Pizza (Variety of Toppings)',
        'Flatbread Pizza',
        'Garlic Bread',
        'Pasta Salad',
        'Fried Pickles',
        'Cucumber Sandwiches',
        'Vegetarian Spring Rolls',
        'Pulled Chicken Sliders',
        'Pulled Beef Sliders',
        'Fried Shrimp',
        'Shrimp Cocktail',
        'Crispy Chicken Wings',
        'Bruschetta',
        'Meat and Cheese Skewers',
        'Grilled Vegetables',
        'Chicken Caesar Wraps',
        'Lemonade',
        'Iced Tea',
        'Fruit Punch',
        'Soda (Cola, Lemon-Lime, Root Beer)',
        'Beer',
        'White Wine',
        'Red Wine',
        'Champagne',
        'Mocktails (Non-Alcoholic)',
        'Sparkling Water',
        'Coffee',
        'Tea',
        'Hot Chocolate',
        'Milkshakes',
        'Smoothies',
        'Apple Cider',
        'Bottled Water',
        'Energy Drinks',
        'Cocktail Mixes (Margarita, Mojito)',
        'Gin and Tonics',
        'Whiskey Sour',
        'Rum Punch',
        'Bloody Mary',
        'Mojito',
        'Pina Colada',
        'Frozen Margaritas',
        'Frozen Daiquiri',
        'Milkshakes (Chocolate, Vanilla, Strawberry)',
        'Ice Cream',
        'Gelato',
        'Sorbet',
        'Cupcakes',
        'Brownies',
        'Chocolate Chip Cookies',
        'Fruit Tart',
        'Cheesecake',
        'Pie (Apple, Cherry, Pumpkin)',
        'Chocolate Fondue',
        'Fruit Salad',
        'Candy Bar',
        'Gummy Bears',
        'Chocolate Bars',
        'Candy Canes',
        'Donuts',
        'Cake Pops',
        'Baklava',
        'Rice Krispies Treats',
        'Cookies and Cream Cupcakes',
        'S mores Ingredients (Marshmallows, Graham Crackers, Chocolate)',
        'Cotton Candy',
        'Popcorn (Flavored or Buttered)',
        'Churros',
        'Tiramisu',
        'Cupcake Decorating Kit',
        'Pudding Cups',
        'Caramel Apples',
        'Frozen Yogurt Toppings',
        'Chocolate Mousse',
        'Fruit Skewers',
        'Pineapple Fried Rice',
        'Grilled Cheese Sandwiches',
        'Waffles with Toppings',
        'Pancakes with Syrup',
        'Breakfast Burritos',
        'Omelette Bar',
        'Bagel Bar',
        'Smoothie Bowl',
        'Cinnamon Rolls',
        'Croissants',
        'French Toast',
        'Hash Browns',
        'Toast with Avocado',
        'Pop-Tarts',
        'Cheese-Stuffed Pretzels',
        'Pretzels with Cheese Dip',
        'Chili',
        'Lasagna',
        'Baked Ziti',
        'Beef Empanadas',
        'Vegetarian Empanadas',
        'Tamales',
        'Quesadillas',
        'Churros with Chocolate Sauce',
        'Sushi Rolls (Variety)',
        'Tempura Shrimp',
        'Ramen',
        'Pasta with Pesto Sauce',
        'Risotto',
        'Ceviche',
        'Paella',
        'Gourmet Pizza (Margherita, BBQ Chicken)',
        'Buffalo Cauliflower Bites'
    ];
     
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name'=>fake()->randomElement($this->foodAndDrinkItems),
            'amount'=>fake()->numberBetween(1,5),
            'unit_price'=>fake()->randomFloat(1,5,20),
        ];
    }
}
